# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Util-DayOfWeek
version:      0.01
version_from: lib/DateTime/Util/DayOfWeek.pm
installdirs:  site
requires:
    DateTime:                      0.2901
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
